name: analytics
description: Simple analytics library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.3 <4.0.0"

resolution: workspace

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: ^1.19.1

  # Firebase
  firebase_analytics: ^11.3.6

  # Local Packages
  logger:
    path: ../logger

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true