name: app_database
description: "Database for the app"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.1
  drift_flutter: 0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.1
  build_runner: 2.4.15

flutter:
  uses-material-design: true