name: app_database
description: "Database for the app"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: 2.23.0
  drift_flutter: 0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: 2.23.1
  build_runner: 2.4.14
  sizzle_lints: 2.1.3
