name: root
description: "Workspace root"

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

dev_dependencies:
  sizzle_lints: ^2.1.7

workspace:
  - app
  # Core
  - core/common
  - core/analytics
  - core/logger
  - core/rest_client
  - core/error_reporter
  - core/ui_library
  - core/database
  # Feature
  - feature/settings
  - feature/home
