name: sizzle_starter
description: Production-ready template for Flutter applications.
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.28.0

  # BLoC
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  # Networking
  http: ^1.2.2
  cronet_http: ^1.3.2
  cupertino_http: ^1.5.1

  # Storing data
  shared_preferences: ^2.3.2
  drift: ^2.20.0
  drift_flutter: ^0.2.0

  # Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.7.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3

  # Utils
  platform_info: ^5.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  intercepted_client: ^0.0.1
  clock: ^1.1.1

dev_dependencies:
  # Testing
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  # Lints
  sizzle_lints: ^2.1.3

  # Utils
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  # Codegen
  drift_dev: ^2.20.1
  build_runner: ^2.4.12
  dart_code_metrics_presets: ^2.16.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
