name: sizzle_starter
description: Your description

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: 1.17.1
  async: 2.11.0
  meta: 1.9.1

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # HTTTP
  http: 0.13.6

  # Router
  auto_route: 7.4.0

  # Firebase
  firebase_analytics: 10.4.2
  firebase_core: 2.13.1

  # l10n
  intl: 0.18.0
  flutter_localizations:
    sdk: flutter

  # Path receiving/manipulation
  path_provider: 2.0.15
  path: 1.8.3

  # Persisting
  drift: 2.8.2
  sqlite3_flutter_libs: 0.5.15
  shared_preferences: 2.1.1

  # Codegen annotations
  json_annotation: 4.8.1

  # Logging
  stack_trace: 1.11.0
  l: 4.0.1
  sentry_flutter: 7.6.3

  # Lints
  sizzle_lints: 1.0.10

  # Helpers
  pure: 0.2.0
  platform_info: 4.0.0
  bloc_concurrency: 0.2.2

  rest_client:
    path: packages/rest_client

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  json_serializable: 6.7.0
  build_runner: 2.4.4
  drift_dev: 2.8.3
  auto_route_generator: 7.1.1

  # Utilities
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_gen_runner: 5.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 100
