name: root
description: "Workspace root"

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0 <4.0.0"

dev_dependencies:
  sizzle_lints: ^2.1.7

workspace:
  - app
  # Core
  - core/common_utils
  - core/common_analytics
  - core/common_logger
  - core/common_rest_client
  - core/common_error_reporter
  - core/common_ui_library
  - core/common_database
