name: sizzle_starter
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # BLoC
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # Codegen
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Networking
  dio: ^5.3.3

  # Persisting
  shared_preferences: ^2.2.2
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: ^7.12.0
  logging: ^1.2.0

  # Utils
  pure: ^0.2.0
  platform_info: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  flutter_native_splash: ^2.3.5
  
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  sizzle_lints: ^2.0.2

  # Utils
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.5

  # Codegen
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  drift_dev: ^2.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
