name: database
description: Database-related logic
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

# Add regular dependencies here.
dependencies:
  drift: 2.10.0
  path: 1.8.3
  path_provider: 2.1.0
  sqlite3_flutter_libs: 0.5.17

dev_dependencies:
  build_runner: 2.4.6
  drift_dev: 2.10.0
  sizzle_lints: ^2.0.1
