name: database
description: Database-related logic
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  drift: 2.8.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  drift_dev: 2.8.3
  lints: ^2.0.0
  test: ^1.21.0
