name: common_analytics
description: Simple analytics library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.41.1 <4.0.0"

resolution: workspace

dependencies:
  # SDK
  flutter:
    sdk: flutter
  collection: 1.19.1

  # Firebase
  firebase_analytics: ^12.0.2

  # Local Packages
  common_logger:
    path: ../common_logger

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.5.3

flutter:
  uses-material-design: true