name: rest_client
description: Rest client
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cronet_http: ^1.6.0
  cupertino_http: ^2.3.0
  http: ^1.5.0
  intercepted_client: 0.0.1
  path: 1.9.1
  meta: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.5.3

flutter:
  uses-material-design: true