name: rest_client
description: Rest client
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cronet_http: 1.3.2
  cupertino_http: 2.0.2
  http: 1.2.2
  intercepted_client: 0.0.1
  path: 1.9.0
  meta: 1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.5
  build_runner: 2.4.14
  sizzle_lints: 2.1.3

flutter:
  uses-material-design: true