name: common_error_reporter
description: Error reporter
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  common_logger:
    path: ../common_logger
  sentry_flutter: ^9.6.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
